name: PHPUnit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpunit-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ 8.1 ]
        dependency-version: [ prefer-stable ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Environment Dependencies
        run: sudo apt-get install poppler-utils

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, bcmath, ctype, fileinfo, json, openssl, pdo, tokenizer, xml
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --prefer-dist

      - name: Execute tests via PHPUnit
        run: ./vendor/bin/phpunit tests
